# Semgrep Configuration for PromptCraft
# Suppresses false positives while maintaining security coverage

rules:
  # Suppress return-not-in-function false positives
  # These are legitimate return statements within try-except blocks
  - id: python.lang.maintainability.return.return-not-in-function
    paths:
      exclude:
        - "src/auth_simple/config.py"
        - "src/monitoring/ab_testing_dashboard.py"
        - "src/auth/models.py"
    message: "Suppressed: Legitimate return statements in try-except blocks"

  # Suppress assert statements in configuration validation
  # These are appropriate for A/B testing parameter validation
  - id: gitlab.bandit.B101
    paths:
      exclude:
        - "src/core/ab_testing_models.py"
    message: "Suppressed: Configuration validation asserts are appropriate"

  # Suppress weak random generation in testing scripts
  # Performance validation scripts use random for test data only
  - id: gitlab.bandit.B311
    paths:
      exclude:
        - "scripts/homelab_performance_validation.py"
    message: "Suppressed: Testing script uses random for non-security purposes"

  # Suppress code-after-return for defensive programming patterns
  - id: python.lang.maintainability.return.code-after-unconditional-return
    metadata:
      category: maintainability
    paths:
      exclude:
        - "src/auth/service_token_manager.py"
    message: "Suppressed: Defensive programming pattern with intentional unreachable code"

# Keep security rules active for legitimate vulnerabilities
# SQL injection rules will remain active until fixed in migration scripts
