services:
  promptcraft-app:
    build: .
    container_name: promptcraft-app
    ports:
      - "127.0.0.1:7860:7860"  # Bind to localhost only
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=random
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src:ro          # Read-only source
      - ./config:/app/config:ro    # Read-only config
      - ./knowledge:/app/knowledge:ro
      - ./logs:/app/logs:rw
    user: "1000:1000"              # Non-root user
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - promptcraft
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promptcraft-api:
    build: .
    container_name: promptcraft-api
    command: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
    ports:
      - "127.0.0.1:8000:8000"     # Bind to localhost only
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=random
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src:ro          # Read-only source
      - ./config:/app/config:ro    # Read-only config
      - ./logs:/app/logs:rw
    user: "1000:1000"              # Non-root user
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - promptcraft
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Code-Server for Journey 3 IDE Integration
  promptcraft-ide:
    image: codercom/code-server:latest
    container_name: promptcraft-ide
    ports:
      - "127.0.0.1:8080:8080"     # Bind to localhost only for cloudflared tunnel
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
    env_file:
      - .env.local
    volumes:
      - ./src:/home/coder/workspace/src:rw
      - ./config:/home/coder/workspace/config:ro
      - ./knowledge:/home/coder/workspace/knowledge:ro
      - ./docs:/home/coder/workspace/docs:rw
      - ./tests:/home/coder/workspace/tests:rw
      - ./configs/code-server:/home/coder/.config:rw
      - ./configs/mcp:/home/coder/.claude:rw
    command: |
      code-server
        --bind-addr 0.0.0.0:8080
        --auth password
        --disable-telemetry
        --user-data-dir /home/coder/.config
        --extensions-dir /home/coder/.local/share/code-server/extensions
        /home/coder/workspace
    user: "1000:1000"              # Non-root user
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - promptcraft
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: promptcraft-redis
    # Remove exposed ports - internal only
    command: redis-server --appendonly yes --appendfsync everysec --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env.local
    volumes:
      - redis-data:/data
    user: "999:999"               # Redis user
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - promptcraft
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  promptcraft:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24    # Smaller subnet

volumes:
  redis-data:
    driver: local

# External Qdrant connection verification
# Note: External Qdrant server configured via QDRANT_HOST environment variable
# This is accessed directly from containers via environment variables
# No container definition needed as it's hosted externally

# Cloudflared Tunnel Integration Notes:
# - All services bind to 127.0.0.1 (localhost) for cloudflared tunnel routing
# - Gradio UI (port 7860): Journey 1, 2, 4 web interface
# - FastAPI (port 8000): API endpoints and backend services
# - Code-Server (port 8080): Journey 3 IDE integration
# - Cloudflared tunnel handles authentication, SSL, and routing
# - No nginx or OAuth2 proxy needed - tunnel provides unified access
#
# Example cloudflared config.yml:
# ingress:
#   - hostname: promptcraft.yourdomain.com
#     path: /ide/*
#     service: http://localhost:8080
#   - hostname: promptcraft.yourdomain.com
#     path: /api/*
#     service: http://localhost:8000
#   - hostname: promptcraft.yourdomain.com
#     path: /
#     service: http://localhost:7860
#   - service: http_status:404
