# OWASP ZAP DAST Configuration for PromptCraft
# This configuration defines security scanning rules and policies

target:
  base_url: "http://localhost:7860"
  health_endpoint: "/health"
  api_endpoints:
    - "/api/v1/"
    - "/docs"
    - "/openapi.json"

scan_policies:
  baseline:
    enabled: true
    include_rules:
      - "10021"  # X-Content-Type-Options Header Missing
      - "10020"  # X-Frame-Options Header Scanner
      - "10017"  # Cross-Domain JavaScript Source File Inclusion
      - "10016"  # Web Browser XSS Protection Not Enabled
      - "10015"  # Incomplete or No Cache-control and Pragma HTTP Header Set
      - "10011"  # Cookie Without Secure Flag
      - "10010"  # Cookie Without HttpOnly Flag
    exclude_rules: []

  api_scan:
    enabled: true
    openapi_spec: "docs/openapi.json"
    include_formats:
      - "json"
      - "xml"

reporting:
  formats:
    - "json"
    - "html"
    - "xml"
    - "md"
  output_dir: "dast-reports"
  include_request_response: false
  include_passive_scan_rules: true

security_levels:
  # Risk levels: High, Medium, Low, Informational
  fail_on_risk_level: "High"
  warn_on_risk_level: "Medium"

authentication:
  # Configuration for authenticated scans (if needed)
  enabled: false
  type: "session"  # session, oauth2, basic

exclusions:
  # URLs to exclude from scanning
  - "*/logout"
  - "*/admin/*"
  - "*/test/*"

scan_options:
  max_duration_minutes: 30
  max_children: 10
  max_depth: 5
  delay_in_ms: 0

docker:
  image: "owasp/zap2docker-stable"
  network_mode: "host"
  memory_limit: "2g"
