# Security configuration for PromptCraft-Hybrid
security:
  # API Security
  api:
    rate_limiting:
      enabled: true
      requests_per_minute: 60
      requests_per_hour: 1000
    authentication:
      type: "api_key"  # Phase 1
      api_key_header: "X-API-Key"
    cors:
      enabled: true
      allowed_origins:
        - "http://localhost:7860"
        - "http://localhost:3000"
        - "http://192.168.1.205:7860"
        - "http://192.168.1.205:3000"
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["*"]
      expose_headers: ["X-Request-ID"]
  # Input Validation
  validation:
    max_query_length: 10000
    max_context_size: 50000
    allowed_file_types: [".md", ".txt", ".json", ".yaml"]
    max_file_size_mb: 10
  # Secrets Management
  secrets:
    provider: "environment"  # Phase 1
    rotation_days: 90
  # Logging
  logging:
    redact_pii: true
    redact_patterns:
      - 'api[_-]?key'
      - 'password'
      - 'secret'
      - 'token'
      - 'ssn'
      - 'credit[_-]?card'
  # Network Security
  network:
    ssl_required: true
    min_tls_version: "1.2"
    trusted_proxies:
      - "127.0.0.1"
      - "::1"
      - "192.168.1.205"
      - "192.168.1.16"
