name: 📝 What The Diff PR Summary

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "dist/**"
      - "build/**"
      - "vendor/**"
      - "*.lock"
      - "*.png"
      - "*.jpg"
      - "*.jpeg"
      - "*.gif"
      - "*.svg"
      - "*.ico"
      - "**/__pycache__/**"
      - "*.pyc"
      - ".pytest_cache/**"
      - "htmlcov/**"
      - "*.egg-info/**"

jobs:
  wtd-summary:
    name: Generate PR Summary
    runs-on: ubuntu-latest
    
    # Skip WTD for bot-authored PRs to avoid unnecessary API calls
    if: |
      github.event.pull_request.user.type != 'Bot' &&
      !contains(github.event.pull_request.user.login, '[bot]')
    
    steps:
      - name: 🎯 What The Diff
        uses: what-the-diff/what-the-diff-action@v1.0.0
        with:
          # WTD API token stored in repository secrets
          api-key: ${{ secrets.WHAT_THE_DIFF_API_KEY }}
          
          # Use shortcode approach for PR description integration
          # This allows workflow-prepare-pr.md to control inclusion
          pr-description-mode: replace
          
          # Focus on meaningful code changes
          focus-on-new-and-changed-files: true
